[build]
  publish = "public"
  command = "npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[build.environment]
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/api/*"
  to = "/index.php/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
